### ISSUE TITLE
Can you please share the slack workspace?

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [OpenDriveLab/End-to-end-Autonomous-Driving#7]
I tried to join the slack as given in readme but could not, so can you please share the workspace name?

**Comment by ilnehc** [comment]
@VeeranjaneyuluToka Please find the updated link
https://opendrivelab.slack.com/join/shared_invite/zt-2ft3dfjoz-6XErfBts4s_8Fen88wO4Jg#/shared-invite/email
